(in-package :flowfps)

(defun cli ()
  (open-apply-write "input.png" "sepia.png" (filter-sepia 30))
  (open-apply-write "input.png" "noise.png" (filter-noise 5 40 5))
  (open-apply-write "noise.png" "noise-lshift.png" (filter-rgb-lshift))
  (open-apply-write "noise.png" "noise-rshift.png" (filter-rgb-rshift))
  (open-apply-write "input.png" "grey.png" (filter-greyscale-average))
  (open-apply-write "grey.png" "grey-darker.png" (filter-decrease-brightness 20))
  (open-apply-write "grey.png" "grey-lighter.png" (filter-increase-brightness 20))
  (format t "Done!~&")
  (finish-output nil))
